version: '1'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3040:3040"
    volumes:
      - ./server.js:/usr/src/app/server.js
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3040/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: on-failure